# Generated by Django 4.2.5 on 2023-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_diffusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='character_prompt',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='example',
            name='negative_prompt',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='example',
            name='style_prompt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
